# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/temp

    steps:
      - checkout

      - run: sudo npm install -g grunt-cli
      
      - run: sudo npm install --save-dev
        
      - run: echo $credentials >> ~/temp/credentials.json
        
      - run: grunt production
