# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:latest
    working_directory: ~/kleips
    steps:
      - checkout

      - restore_cache:
          key: v3-dependencies-{{ checksum "~/kleips/package.json" }}

      - run:
          name: Install Hexo-CLI
          command: sudo npm install -g hexo-cli
      - run:
          name: Install Dependencies
          command: sudo npm install

      - save_cache:
          key: v3-dependencies-{{ checksum "~/kleips/package.json" }}
          paths:
            - ~/kleips/node_modules

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/kleips
    steps:
      - checkout

      - restore_cache:
          key: v3-dependencies-{{ checksum "~/kleips/package.json" }}

      - run:
          name: Build with Branch Check
          command: |
            case $CIRCLE_BRANCH in
            master)
              npm run build:production
              ;;
            develop)
              npm run build:staging
              ;;
            *)
              npm run build:dev
              ;;
            esac

      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/kleips/public

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/kleips
    steps:
      - checkout

      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v3-dependencies-{{ checksum "~/kleips/package.json" }}

      - run:
          name: Deploy with Branch Check
          command: |
            case $CIRCLE_BRANCH in
            master)
              npm run deploy:production
              ;;
            develop)
              npm run deploy:staging
              ;;
            *)
              echo 'Skipping deployment.'
              ;;
            esac

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - deploy:
          requires:
            - dependencies
            - build
          filters:
            branches:
              only:
                - master
                - develop